apiVersion: v1
kind: Pod
metadata:
  name: appname
  namespace: default
  labels:
    app: appname
spec:
  volumes:
  - name: zeroci-pub-key
    hostPath:
      path: /home/rancher/.ssh/id_rsa.pub
      type: File
  hostname: appname
  containers:
  - name: appname
    image: "image_name"
    command: ["/bin/bash", "-ce", "service ssh restart && tail -f /dev/null"]
    env:
    - name: DEBIAN_FRONTEND
      value: noninteractive
    ports:
    - containerPort: 22
    volumeMounts:
      - mountPath: /root/.ssh/authorized_keys
        name: zeroci-pub-key
        readOnly: true
